[tools]
deno = "2.4"
lefthook = "1.12.1"

[hooks]
postinstall = ["deno install", "lefthook install"]

[tasks.dev]
run = "deno task dev"

[tasks.start]
run = "deno task start"

[tasks.test]
run = "deno task test"

[tasks.lint]
run = ["deno task format", "deno check"]
alias = "format"
